### ISSUE TITLE
(Vagrant)  Cookbook gradle not found.

### ISSUE THREAD

**Issue by ericfrancis** [michaelklishin/gradle-chef-cookbook#8]
## Berksfile 
```
source 'https://supermarket.chef.io'

metadata

cookbook 'gradle', git: 'https://github.com/michaelklishin/gradle-chef-cookbook'
```

## cookbook/application/recipes/default.rb
```
include_recipe 'apt'
include_recipe 'java'
include_recipe 'gradle::tarball'
```

## Vagrantfile
```
...
app.vm.provision "chef_zero" do |chef|
    chef.add_recipe "application"
end
...
```

## Error
```
==> app: ================================================================================
==> app: Recipe Compile Error in /var/chef/cache/cookbooks/application/recipes/default.rb
==> app: ================================================================================
==> app:
==> app:
==> app: Chef::Exceptions::CookbookNotFound
==> app: ----------------------------------
==> app: Cookbook gradle not found. If you're loading gradle from another cookbook, make sure you configure the dependency in your metadata
```

**Comment by michaelklishin** [comment]
This looks like a metadata issue.

**Comment by ericfrancis** [comment]
@michaelklishin What do you mean? I think it may be a `vagrant-berkshelf` issue, but I'm not sure.

**Comment by michaelklishin** [comment]
This cookbook's metadata file lacks cookbook name. Compare it to [cassandra-dse](https://github.com/michaelklishin/cassandra-chef-cookbook/blob/master/metadata.rb), for example.

**Comment by kbruner** [comment]
The lack of name in the metadata.rb also causes issues for chefspec in cookbooks that depend on this cookbook.  Any reason the cookbook name hasn't been added?

**Comment by michaelklishin** [comment]
@kbruner nobody submitted a pull requests and I'm busy with other projects I'm involved with.
